#!/usr/bin/env bash
# Stage 1 of `make publish`: commit + push the release metadata
# (Info.plist + docs/appcast.xml + docs/release-notes/<VERSION>.md) and wait
# for GitHub Pages to serve the new appcast before yielding control to
# `make publish-release`.
#
# Idempotent: if Pages already serves the current version we skip the
# commit/push/poll entirely. This makes `make publish` safe to re-run after
# a publish-release failure.
#
# Inputs:
#   - Resources/Info.plist         (CFBundleShortVersionString — source of truth)
#   - dist/Seshctl-<VERSION>.dmg   (produced by `make dist`; checked but not consumed)
#   - docs/appcast.xml             (regenerated by `make appcast`, must advertise <VERSION>)
#   - docs/release-notes/<VERSION>.md (written manually as pre-release step)
#
# Side effects:
#   - Single git commit on the current branch (must be `main`) titled "Release v<VERSION>"
#   - git push to origin
#   - Blocks until Pages serves the new appcast or 5min timeout

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_DIR="$( cd "${SCRIPT_DIR}/.." && pwd )"
cd "${REPO_DIR}"

VERSION="$(plutil -extract CFBundleShortVersionString raw -o - Resources/Info.plist)"
if [[ -z "${VERSION}" ]]; then
  echo "Error: could not read CFBundleShortVersionString from Resources/Info.plist" >&2
  exit 1
fi

APPCAST_URL="https://julo15.github.io/seshctl/appcast.xml"
DMG_PATH="dist/Seshctl-${VERSION}.dmg"
NOTES_PATH="docs/release-notes/${VERSION}.md"
APPCAST_PATH="docs/appcast.xml"
INFO_PLIST="Resources/Info.plist"

echo "==> Publish docs for v${VERSION}"

# --- Idempotency: if Pages already advertises this version, nothing to do. ---
if curl -fsS "${APPCAST_URL}" 2>/dev/null \
    | grep -q "sparkle:shortVersionString>${VERSION}<"; then
  echo "  Pages already serves v${VERSION} — skipping publish-docs."
  exit 0
fi

# --- Pre-flight checks ---

# 1. On main branch.
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "${BRANCH}" != "main" ]]; then
  echo "Error: publish-docs must run on 'main' (currently on '${BRANCH}')." >&2
  exit 1
fi

# 2. Artifact + metadata files must exist.
if [[ ! -f "${DMG_PATH}" ]]; then
  echo "Error: ${DMG_PATH} not found. Run \`make dist\` first." >&2
  exit 1
fi
if [[ ! -f "${NOTES_PATH}" ]]; then
  echo "Error: ${NOTES_PATH} not found. Write the release notes before publishing." >&2
  exit 1
fi
if [[ ! -f "${APPCAST_PATH}" ]]; then
  echo "Error: ${APPCAST_PATH} not found. Run \`make appcast\` first." >&2
  exit 1
fi

# 3. Appcast must already advertise the current version (proves `make appcast`
#    ran against the bumped Info.plist).
if ! grep -q "sparkle:shortVersionString>${VERSION}<" "${APPCAST_PATH}"; then
  echo "Error: ${APPCAST_PATH} does not advertise <sparkle:shortVersionString>${VERSION}</...>" >&2
  echo "       Did you re-run \`make appcast\` after bumping Info.plist?" >&2
  exit 1
fi

# 4. No existing v<VERSION> tag locally or on origin.
if git rev-parse --verify --quiet "refs/tags/v${VERSION}" >/dev/null; then
  echo "Error: tag v${VERSION} already exists locally." >&2
  exit 1
fi
if git ls-remote --tags origin "refs/tags/v${VERSION}" 2>/dev/null | grep -q "v${VERSION}"; then
  echo "Error: tag v${VERSION} already exists on origin." >&2
  exit 1
fi

# 5. `gh` is authenticated (publish-release needs it; fail fast here).
if ! gh auth status >/dev/null 2>&1; then
  echo "Error: \`gh auth status\` failed. Run \`gh auth login\` first." >&2
  exit 1
fi

# 6. Working tree contains the three expected paths and nothing else.
#    `git status --porcelain` returns "XY path" entries. We accept M/A/?? states
#    for the three expected paths and refuse if any other path shows up.
EXPECTED_PATHS=("${INFO_PLIST}" "${APPCAST_PATH}" "${NOTES_PATH}")
mapfile -t actual_paths < <(git status --porcelain | awk '{print $2}' | sort)
expected_sorted=$(printf '%s\n' "${EXPECTED_PATHS[@]}" | sort)
actual_joined=$(printf '%s\n' "${actual_paths[@]}")
if [[ "${actual_joined}" != "${expected_sorted}" ]]; then
  echo "Error: working tree drift. Expected exactly these paths changed:" >&2
  printf '         %s\n' "${EXPECTED_PATHS[@]}" >&2
  echo "       Actual:" >&2
  printf '         %s\n' "${actual_paths[@]}" >&2
  echo "       Stash or commit unrelated changes first." >&2
  exit 1
fi

echo "==> Pre-flight checks passed."

# --- Commit + push ---

echo "==> Staging metadata files ..."
git add "${INFO_PLIST}" "${APPCAST_PATH}" "${NOTES_PATH}"

echo "==> Committing \"Release v${VERSION}\" ..."
git commit -m "Release v${VERSION}"

echo "==> Pushing to origin/main ..."
git push origin main

# --- Poll Pages ---

echo "==> Polling ${APPCAST_URL} until v${VERSION} appears (5min timeout) ..."
TIMEOUT_S=300
INTERVAL_S=5
START_TS=$(date +%s)
while true; do
  if curl -fsS "${APPCAST_URL}" 2>/dev/null \
      | grep -q "sparkle:shortVersionString>${VERSION}<"; then
    elapsed=$(( $(date +%s) - START_TS ))
    echo "  Pages serves v${VERSION} (after ${elapsed}s)."
    break
  fi
  elapsed=$(( $(date +%s) - START_TS ))
  if (( elapsed >= TIMEOUT_S )); then
    echo "" >&2
    echo "Error: Pages did not serve v${VERSION} within ${TIMEOUT_S}s." >&2
    echo "       Check the repo's Actions tab for a failed Pages build, then re-run \`make publish\`." >&2
    echo "       publish-docs is idempotent — re-running will skip the commit/push if Pages catches up." >&2
    exit 1
  fi
  printf '  .'
  sleep "${INTERVAL_S}"
done

echo "==> publish-docs done. Run \`make publish-release\` (or \`make publish\` again to chain)."
